### ISSUE TITLE
[MILESTONE] Design/Implemenent Frontend

### ISSUE THREAD

**Issue by mbucataru** [btcook2004/RoommateRoundup#32]
This Milestone issue encompasses the design and implementation of the pages of the website.

This includes:
**Homepage** (a page that displays sign-up/sign-in buttons on a sleek background)
**Sign-up/sign-in page** (self-explanatory)
**Swiping Page** (includes the actual logic of being able to "swipe" the card (not just click buttons)
**Profile Page**
**Preferences Questionnaire Page**
**Messages Page**

These pages should all be populated with **sample data**. This issue **does not** encompass linking anything to the backend (i.e: registering swipes). It simply refers to designing and implementing the **look and feel** of the website. Some required pages may be missing from the issue, they can be added in edits or comments.

**Comment by btcook2004** [comment]
Closing the issue. Everything is done on the front end minus the messaging turned matches table
