### ISSUE TITLE
[MILESTONE] Design/Implement Backend Logic

### ISSUE THREAD

**Issue by mbucataru** [btcook2004/RoommateRoundup#33]
This milestone encompasses the design and implementation of the backend logic.

This includes:
**Designing** and **implementing** the questionnaire/swiping algorithm (if User A has answer set A, User B has answer set B, and User C has answer set C, which users should we **not match**, which users should be matched at **higher priority**, etc.)
**Finalizing the database schema**: This may include a group session where every table is scrutinized, but it also includes the design of the questionnaire answer table schema (which is currently a mess).
**Designing** and **implementing** the messaging system.
**Designing** and **implementing** the login system (hashing, security, should it contain an email, etc)

**Comment by btcook2004** [comment]
Closing this issue to make new ones with more atomic issues
