### ISSUE TITLE
Edit Profile on Dashboard

### ISSUE THREAD

**Issue by btcook2004** [btcook2004/RoommateRoundup#59]
This link could be interactive. It could display recommendations to the user about questions that have not yet been filled out. If all questions are filled out and the user has uploaded a profile picture, then it could say something like "All good to go". No matter the state, it should link to the edit profile page. Use sample data for now. We will populate it with real data later.

**Comment by retrospecht** [comment]
The dashboard page uses a post request to check if the profile has filled out or not. #87
